### ISSUE TITLE
Nested configurations don't get created

### ISSUE THREAD

**Issue by juanibiapina** [railsware/caphub#5] opened 2013-10-22 19:24 UTC
Ruby: 2.0.0-p247

Fresh project:

```
caphub testproject
```

Change into the project, bundle and create two configs:

```
cd testproject
mkdir -p config/deploy/blog
touch config/deploy/blog.rb
touch config/deploy/blog/staging.rb
```

List tasks:

```
bundle exec cap -T
```

You'll see the blog task but not the blog:staging task.

Running `bundle exec cap blog:staging` confirms the missing task.

Gemfile.lock:

```
GEM
  remote: https://rubygems.org/
  specs:
    capistrano (3.0.0)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 0.0.23)
    capistrano-multiconfig (3.0.2)
      capistrano (>= 3.0.0)
    i18n (0.6.5)
    net-scp (1.1.2)
      net-ssh (>= 2.6.5)
    net-ssh (2.7.0)
    rake (10.1.0)
    sshkit (1.1.0)
      net-scp
      net-ssh
      term-ansicolor
    term-ansicolor (1.2.2)
      tins (~> 0.8)
    tins (0.12.0)

PLATFORMS
  ruby

DEPENDENCIES
  capistrano (>= 3.0.0)
  capistrano-multiconfig (>= 3.0.0)
```

**Comment by rosenfeld** [comment] 2013-10-22 19:26
I can reproduce it here

**Comment by le0pard** [comment] 2013-10-22 20:22
Interesting. Can you guys try this patch for capistrano https://github.com/capistrano/capistrano/pull/715 and check if it also contain such problem?

**Comment by ayanko** [comment] 2013-10-22 20:38
<pre>
[aryan@thinkpad ~]$ cd /tmp
[aryan@thinkpad tmp]$ ruby --version
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-linux]
[aryan@thinkpad tmp]$ gem install caphub
Fetching: caphub-0.1.1.gem (100%)
Successfully installed caphub-0.1.1
1 gem installed
[aryan@thinkpad tmp]$ caphub --help
Usage: caphub [path]
    -c, --cap                        Capistrano version 2 or 3
    -h, --help                       Show this message
    -v, --version                    Show version
[aryan@thinkpad tmp]$ caphub testproject
Creating directory testproject
Creating capistrano skeleton in testproject
Initializating git repository in testproject
[aryan@thinkpad tmp]$ cd testproject/
[aryan@thinkpad (master) testproject]$ mkdir -p config/deploy/blog
[aryan@thinkpad (master) testproject]$ touch config/deploy/blog.rb
[aryan@thinkpad (master) testproject]$ touch config/deploy/blog/staging.rb
[aryan@thinkpad (master) testproject]$ bundle
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Using rake (10.1.0) 
Using i18n (0.6.5) 
Using net-ssh (2.7.0) 
Using net-scp (1.1.2) 
Using tins (0.12.0) 
Using term-ansicolor (1.2.2) 
Using sshkit (1.1.0) 
Using capistrano (3.0.0) 
Installing capistrano-multiconfig (3.0.2) 
Using bundler (1.3.5) 
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
[aryan@thinkpad (master) testproject]$ bundle exec cap -T
cap blog:staging                   # Load blog:staging configuration
cap deploy                         # Deploy a new release
cap deploy:check                   # Check required files and directories exist
cap deploy:check:directories       # Check shared and release directories exist
cap deploy:check:linked_dirs       # Check directories to be linked exist in shared
cap deploy:check:linked_files      # Check files to be linked exist in shared
cap deploy:check:make_linked_dirs  # Check directories of files to be linked exist in shared
cap deploy:cleanup                 # Clean up old releases
cap deploy:cleanup_rollback        # Remove and archive rolled-back release
cap deploy:finished                # Finished
cap deploy:finishing               # Finish the deployment, clean up server(s)
cap deploy:finishing_rollback      # Finish the rollback, clean up server(s)
cap deploy:log_revision            # Log details of the deploy
cap deploy:published               # Published
cap deploy:publishing              # Publish the release
cap deploy:revert_release          # Revert to previous release timestamp
cap deploy:reverted                # Reverted
cap deploy:reverting               # Revert server(s) to previous release
cap deploy:rollback                # Rollback to previous release
cap deploy:started                 # Started
cap deploy:starting                # Start a deployment, make sure server(s) ready
cap deploy:symlink:linked_dirs     # Symlink linked directories
cap deploy:symlink:linked_files    # Symlink linked files
cap deploy:symlink:release         # Symlink release to current
cap deploy:symlink:shared          # Symlink files and directories from shared to release
cap deploy:updated                 # Updated
cap deploy:updating                # Update server(s) by setting up a new release
cap install                        # Install Capistrano, cap install STAGES=staging,production
</pre>

<pre>
[aryan@thinkpad (master) testproject]$ cap --version
Capistrano Version: 3.0.0 (Rake Version: 10.1.0)
[aryan@thinkpad (master) testproject]$ caphub --version
0.1.1
</pre>

**Comment by ayanko** [comment] 2013-10-22 20:40
Can't reproduce.

**Comment by ayanko** [comment] 2013-10-22 21:33
Fixed in capistrano-multiconfig v3.0.3

**Closed as completed** 2013-10-22 21:34 UTC

**Comment by rosenfeld** [comment] 2013-10-23 10:43
Thank you. `bundle update capistrano-multiconfig` fixed it here but I still think you should release a new version depending on capistrano-multiconfig >= 3.0.3...

**Comment by ayanko** [comment] 2013-10-23 10:57
caphub v0.1.2 released

**Comment by rosenfeld** [comment] 2013-10-23 10:58
thanks! :)

**Comment by juanibiapina** [comment] 2013-10-23 11:29
Thanks xD
